[project]
name = "pydemo"
version = "0.0.1"
description = "A small example package"
authors = [
  { name="Example Author", email="author@example.com" },
]
readme = {file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "fastapi >= 0.105.0",
    "requests >= 2.0.0",
]

[project.urls]
"Homepage" = "https://apmath.spbu.ru"
"Bug Tracker" = "https://github.com/pydemo"


[project.optional-dependencies]
inference = [
    "tqdm >= 4.66.0"
]

[dependency-groups]
dev = [
    "mypy >= 1.13.0",
    "ty",
    "ruff >= 0.8.3",
    "isort >= 5.3.12",
    "pytest >= 8.3.4"
]

[project.scripts]
run-pydemo = "pydemo.cli:main"

[tool.pytest.ini_options]
addopts = "-v"
testpaths = [
    "tests",
]

[tool.isort]
profile = "black"
src_paths = ["pydemo", "test"]

[tool.mypy]
disallow_untyped_defs = false
disallow_incomplete_defs = false
follow_imports = "normal"
pretty = true
show_column_numbers = true
show_error_codes = true
warn_no_return = false
warn_unused_ignores = true

[tool.black]
skip-string-normalization = true

[tool.ruff]
line-length = 120

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
